[build]
target = "i686-averion.json"

[unstable]
build-std = ["core", "compiler_builtins"] 
build-std-features = ["compiler-builtins-mem"] 
json-target-spec = true

[target.i686-averion]
linker = "rust-lld"

rustflags = [
    "-Zunstable-options",
    "-C", "link-arg=-Tlinker.ld",
    "-C", "link-arg=target/boot.o",
]